/* Generated by murmur_artwork_pipeline_v0_4.py.
 * Murmur artwork is a seeded emotional field, not a poster.
 */

export type ArtworkBucket =
  | "luminist_air"
  | "sublime_terrain"
  | "tidal_mineral"
  | "pastoral_memory"
  | "nocturne_metro"
  | "printed_signal"
  | "stage_heat"
  | "interior_reverie"
  | "hypermodern_void";

export type MurmurArtwork = {
  id: string;
  bucket: ArtworkBucket;
  title: string;
  artist: string;
  year?: string;
  source: string;
  sourceId: string;
  sourceUrl: string;
  imagePath: string;
  license: "CC0" | "Public Domain" | "Internal";
  tags: string[];
  genreWeights: Record<string, number>;
  moodWeights: Record<string, number>;
  energyRange: [number, number];
  palette?: string[];
  composition?: string;
  figurePresence?: string;
  backgroundFit: number;
  crop: { x: number; y: number; scale: number };
  curatorNote?: string;
};

export type SongVisualFacets = {
  id: string;
  genre?: string;
  mood?: string;
  energy?: number;
  scene?: string;
  instrument?: string;
  tags?: string[];
};

export const ARTWORK_BUCKETS = {
  "luminist_air": {
    "name": "光亮静气",
    "visualStandard": "空气、低地平线、海岸、静止、淡光；背景要像一层浅呼吸，不像风景明信片。",
    "musicFit": [
      "ambient",
      "solo piano",
      "music box",
      "低能量",
      "serene",
      "melancholic",
      "weightless"
    ],
    "curationNote": "优先空、远、低对比；水平线和水面要能承托唱片与波形。"
  },
  "sublime_terrain": {
    "name": "崇高地貌",
    "visualStandard": "山、森林、峡谷、废墟、巨大尺度；人可以存在，但必须很小。",
    "musicFit": [
      "cinematic",
      "orchestral",
      "post-rock",
      "triumphant",
      "mysterious",
      "中高能量"
    ],
    "curationNote": "避免奇幻游戏感；选择真实自然尺度带来的敬畏。"
  },
  "tidal_mineral": {
    "name": "潮汐矿物",
    "visualStandard": "海、岩石、浪、矿物、水彩力量；不要海滩旅游感。",
    "musicFit": [
      "surf rock",
      "dub",
      "bossa nova",
      "breakbeat",
      "glowing",
      "hypnotic"
    ],
    "curationNote": "海水要像材料，不是度假背景；岩石和水的结构感很重要。"
  },
  "pastoral_memory": {
    "name": "田野记忆",
    "visualStandard": "湖、田野、旧天气、柔软回忆；不甜，不田园广告。",
    "musicFit": [
      "lo-fi",
      "folk",
      "dream pop",
      "bedroom",
      "nostalgic",
      "cozy",
      "bittersweet"
    ],
    "curationNote": "像旧日天气留下来的声场，适合低速旋律和私密回忆。"
  },
  "nocturne_metro": {
    "name": "夜城雨光",
    "visualStandard": "夜、水面、雨街、烟雾、城市反光；湿、暗、会呼吸。",
    "musicFit": [
      "trip hop",
      "deep house",
      "city pop",
      "garage",
      "smoky",
      "brooding",
      "starlit"
    ],
    "curationNote": "Rain 不只是天气，而是城市表面的反射、烟和速度。"
  },
  "printed_signal": {
    "name": "版画信号",
    "visualStandard": "版画、线条、植物、图谱、符号感；像被收藏的声纹。",
    "musicFit": [
      "koto",
      "guzheng",
      "gamelan",
      "minimal techno",
      "baroque",
      "mysterious"
    ],
    "curationNote": "图像要有手工线条和档案气质，适合东方乐器和极简重复。"
  },
  "stage_heat": {
    "name": "舞台热量",
    "visualStandard": "人群、舞台、点彩、公共节奏；人物作为节奏，不是主角。",
    "musicFit": [
      "disco",
      "funk",
      "swing",
      "party energy",
      "playful",
      "euphoric"
    ],
    "curationNote": "不是夜店海报；是公共空间里的温度、节拍和流动。"
  },
  "interior_reverie": {
    "name": "室内出神",
    "visualStandard": "房间、窗、床、桌子、宠物、静物、私密空间；低声、近距离。",
    "musicFit": [
      "bedroom",
      "lullaby",
      "neo-soul",
      "lo-fi",
      "cozy",
      "serene"
    ],
    "curationNote": "适合做温柔辅助背景；避免强脸和过强叙事。"
  },
  "hypermodern_void": {
    "name": "超现代空场",
    "visualStandard": "早期抽象、科学图像、几何、深色、未来感；深而净，不赛博。",
    "musicFit": [
      "synthwave",
      "techno",
      "vaporwave",
      "ambient electronic",
      "minimal techno",
      "starlit",
      "hypnotic"
    ],
    "curationNote": "从艺术史和科学档案里找未来感；避免 AI fantasy、NFT 感和霓虹俗套。"
  }
} as const;

export const MURMUR_ARTWORKS = [
  {
    "id": "luminist_air-met-11307",
    "bucket": "luminist_air",
    "title": "Eaton’s Neck, Long Island",
    "artist": "John Frederick Kensett",
    "year": "1872",
    "source": "met",
    "sourceId": "11307",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11307",
    "imagePath": "/artworks/luminist_air/met-11307-eatons-neck-long-island.jpg",
    "license": "Public Domain",
    "tags": [
      "luminism",
      "shore",
      "still water",
      "low horizon",
      "gray blue",
      "quiet"
    ],
    "genreWeights": {
      "ambient": 2.8,
      "solo piano": 2.5,
      "music box": 1.8,
      "guzheng": 1.2
    },
    "moodWeights": {
      "serene": 2.8,
      "melancholic": 2.0,
      "weightless": 2.2,
      "cozy": 0.8
    },
    "energyRange": [
      0.05,
      0.5
    ],
    "palette": [
      "#8E9588",
      "#8F968A",
      "#474231",
      "#85856E",
      "#A2A291"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.93,
    "crop": {
      "x": 0.5,
      "y": 0.55,
      "scale": 1.03
    },
    "curatorNote": "Almost no event, just air and water; ideal as a low-energy field behind waveform UI."
  },
  {
    "id": "luminist_air-met-11309",
    "bucket": "luminist_air",
    "title": "Gathering Storm on Long Island Sound",
    "artist": "John Frederick Kensett",
    "year": "1872",
    "source": "met",
    "sourceId": "11309",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11309",
    "imagePath": "/artworks/luminist_air/met-11309-gathering-storm-long-island-sound.jpg",
    "license": "Public Domain",
    "tags": [
      "luminism",
      "storm",
      "trees",
      "sound",
      "brooding air",
      "coast"
    ],
    "genreWeights": {
      "ambient": 2.0,
      "solo piano": 1.8,
      "post-rock": 1.4
    },
    "moodWeights": {
      "brooding": 2.2,
      "melancholic": 2.1,
      "serene": 1.7,
      "mysterious": 1.5
    },
    "energyRange": [
      0.2,
      0.68
    ],
    "palette": [
      "#443325",
      "#A49986",
      "#B6A895",
      "#7E6F56",
      "#C9B6A1"
    ],
    "composition": "center_mass",
    "figurePresence": "none",
    "backgroundFit": 0.82,
    "crop": {
      "x": 0.48,
      "y": 0.5,
      "scale": 1.08
    },
    "curatorNote": "A darker Kensett for rainy low-energy tracks and suspended tension."
  },
  {
    "id": "luminist_air-met-11311",
    "bucket": "luminist_air",
    "title": "Lake George",
    "artist": "John Frederick Kensett",
    "year": "1869",
    "source": "met",
    "sourceId": "11311",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11311",
    "imagePath": "/artworks/luminist_air/met-11311-lake-george.jpg",
    "license": "Public Domain",
    "tags": [
      "luminism",
      "lake",
      "mountain",
      "still water",
      "low horizon",
      "serene"
    ],
    "genreWeights": {
      "ambient": 2.7,
      "solo piano": 2.4,
      "music box": 1.6,
      "folk": 1.0
    },
    "moodWeights": {
      "serene": 2.8,
      "weightless": 2.0,
      "melancholic": 1.5
    },
    "energyRange": [
      0.08,
      0.55
    ],
    "palette": [
      "#4B3E2A",
      "#88816C",
      "#AFA994",
      "#C0B9A5",
      "#CCC6B5"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.91,
    "crop": {
      "x": 0.5,
      "y": 0.55,
      "scale": 1.04
    },
    "curatorNote": "Broad lake air and mountain haze; a quiet sleeve field for low-energy pieces."
  },
  {
    "id": "luminist_air-met-11314",
    "bucket": "luminist_air",
    "title": "Lake George, Free Study",
    "artist": "John Frederick Kensett",
    "year": "1872",
    "source": "met",
    "sourceId": "11314",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11314",
    "imagePath": "/artworks/luminist_air/met-11314-lake-george-free-study.jpg",
    "license": "Public Domain",
    "tags": [
      "luminism",
      "lake",
      "free study",
      "turquoise",
      "tiny boat",
      "air"
    ],
    "genreWeights": {
      "ambient": 2.6,
      "solo piano": 2.4,
      "guzheng": 1.2,
      "folk": 1.0
    },
    "moodWeights": {
      "serene": 2.7,
      "weightless": 2.2,
      "melancholic": 1.4
    },
    "energyRange": [
      0.08,
      0.52
    ],
    "palette": [
      "#5B7E78",
      "#B0B8BC",
      "#7A938F",
      "#C1B9B3",
      "#CAC1BA"
    ],
    "composition": "low_horizon",
    "figurePresence": "tiny",
    "backgroundFit": 0.9,
    "crop": {
      "x": 0.52,
      "y": 0.52,
      "scale": 1.05
    },
    "curatorNote": "A spare lake study with enough openness to sit behind title and waveform."
  },
  {
    "id": "luminist_air-met-11315",
    "bucket": "luminist_air",
    "title": "Lake George, New York",
    "artist": "John Frederick Kensett",
    "year": "1872",
    "source": "met",
    "sourceId": "11315",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11315",
    "imagePath": "/artworks/luminist_air/met-11315-lake-george-new-york.jpg",
    "license": "Public Domain",
    "tags": [
      "luminism",
      "lake",
      "mist",
      "monochrome",
      "atmospheric perspective"
    ],
    "genreWeights": {
      "ambient": 2.8,
      "solo piano": 2.2,
      "lullaby": 1.4
    },
    "moodWeights": {
      "serene": 2.9,
      "weightless": 2.3,
      "melancholic": 1.6
    },
    "energyRange": [
      0.05,
      0.45
    ],
    "palette": [
      "#ABABAB",
      "#949494",
      "#444444",
      "#B2B2B2",
      "#BBBBBB"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.86,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.06
    },
    "curatorNote": "Nearly monochrome lake air; very usable when the song wants low emotional pressure."
  },
  {
    "id": "luminist_air-met-11325",
    "bucket": "luminist_air",
    "title": "Sunset on the Sea",
    "artist": "John Frederick Kensett",
    "year": "1872",
    "source": "met",
    "sourceId": "11325",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11325",
    "imagePath": "/artworks/luminist_air/met-11325-sunset-on-the-sea.jpg",
    "license": "Public Domain",
    "tags": [
      "luminism",
      "sunset",
      "sea",
      "horizon",
      "pure light",
      "minimal"
    ],
    "genreWeights": {
      "ambient": 2.5,
      "solo piano": 2.2,
      "dream pop": 1.6
    },
    "moodWeights": {
      "serene": 2.7,
      "starlit": 1.9,
      "weightless": 2.0,
      "glowing": 2.0
    },
    "energyRange": [
      0.08,
      0.58
    ],
    "palette": [
      "#7B6749",
      "#967346",
      "#564E37",
      "#B67931",
      "#BF8633"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.94,
    "crop": {
      "x": 0.5,
      "y": 0.48,
      "scale": 1.03
    },
    "curatorNote": "A pure horizon field: almost nothing happens, which is why it works."
  },
  {
    "id": "sublime_terrain-manual-saam-1967.136.7",
    "bucket": "sublime_terrain",
    "title": "Alaskan Coast Range",
    "artist": "Albert Bierstadt",
    "year": "1889",
    "source": "manual",
    "sourceId": "saam-1967.136.7",
    "sourceUrl": "https://americanart.si.edu/artwork/alaskan-coast-range-2058",
    "imagePath": "/artworks/sublime_terrain/saam-1967-136-7-alaskan-coast-range.jpg",
    "license": "Public Domain",
    "tags": [
      "alaska",
      "mountain",
      "lake",
      "glacier",
      "hudson river school",
      "sublime"
    ],
    "genreWeights": {
      "cinematic": 2.8,
      "orchestral": 2.5,
      "post-rock": 2.2,
      "ambient": 1.2
    },
    "moodWeights": {
      "triumphant": 2.2,
      "mysterious": 2.0,
      "starlit": 1.4,
      "serene": 1.1
    },
    "energyRange": [
      0.42,
      0.95
    ],
    "palette": [
      "#757377",
      "#8A8483",
      "#5D5553",
      "#A9A39C",
      "#B3AB9D"
    ],
    "composition": "deep_perspective",
    "figurePresence": "none",
    "backgroundFit": 0.83,
    "crop": {
      "x": 0.5,
      "y": 0.54,
      "scale": 1.04
    },
    "curatorNote": "A small song set against huge terrain; the core Cursor-like “interface before history” feeling."
  },
  {
    "id": "sublime_terrain-met-10154",
    "bucket": "sublime_terrain",
    "title": "The Rocky Mountains, Lander’s Peak",
    "artist": "Albert Bierstadt",
    "year": "1863",
    "source": "met",
    "sourceId": "10154",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/10154",
    "imagePath": "/artworks/sublime_terrain/met-10154-rocky-mountains-landers-peak.jpg",
    "license": "Public Domain",
    "tags": [
      "rocky mountains",
      "frontier",
      "lake",
      "waterfall",
      "large scale",
      "sublime"
    ],
    "genreWeights": {
      "cinematic": 2.8,
      "orchestral": 2.5,
      "post-rock": 2.1
    },
    "moodWeights": {
      "triumphant": 2.3,
      "glowing": 1.8,
      "mysterious": 1.5
    },
    "energyRange": [
      0.5,
      0.98
    ],
    "palette": [
      "#5F532D",
      "#363322",
      "#BCD4DB",
      "#D8DDD8",
      "#A0A7A5"
    ],
    "composition": "low_horizon",
    "figurePresence": "tiny",
    "backgroundFit": 0.74,
    "crop": {
      "x": 0.5,
      "y": 0.48,
      "scale": 1.08
    },
    "curatorNote": "Canonical and bold, so use sparingly; strong for cinematic peaks and high-energy orchestral outputs."
  },
  {
    "id": "sublime_terrain-met-10481",
    "bucket": "sublime_terrain",
    "title": "Heart of the Andes",
    "artist": "Frederic Edwin Church",
    "year": "1859",
    "source": "met",
    "sourceId": "10481",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/10481",
    "imagePath": "/artworks/sublime_terrain/met-10481-heart-of-the-andes.jpg",
    "license": "Public Domain",
    "tags": [
      "hudson river school",
      "andes",
      "mountain",
      "waterfall",
      "botanical detail",
      "sublime",
      "panorama"
    ],
    "genreWeights": {
      "cinematic": 2.9,
      "orchestral": 2.7,
      "post-rock": 2.2,
      "ambient": 1.2
    },
    "moodWeights": {
      "triumphant": 2.2,
      "mysterious": 1.8,
      "glowing": 1.8,
      "serene": 1.2
    },
    "energyRange": [
      0.48,
      0.98
    ],
    "palette": [
      "#B6B8B7",
      "#392A0E",
      "#674F22",
      "#846E42",
      "#52441C"
    ],
    "composition": "center_mass",
    "figurePresence": "tiny",
    "backgroundFit": 0.76,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.08
    },
    "curatorNote": "Dense but vast; good for songs that need expedition-scale lift without a modern fantasy look."
  },
  {
    "id": "sublime_terrain-met-10480",
    "bucket": "sublime_terrain",
    "title": "The Aegean Sea",
    "artist": "Frederic Edwin Church",
    "year": "ca. 1877",
    "source": "met",
    "sourceId": "10480",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/10480",
    "imagePath": "/artworks/sublime_terrain/met-10480-aegean-sea.jpg",
    "license": "Public Domain",
    "tags": [
      "ruins",
      "rainbow",
      "sea",
      "ancient landscape",
      "storm light",
      "sublime"
    ],
    "genreWeights": {
      "cinematic": 2.4,
      "orchestral": 2.1,
      "post-rock": 1.7,
      "ambient electronic": 1.5
    },
    "moodWeights": {
      "mysterious": 2.1,
      "glowing": 2.0,
      "starlit": 1.7,
      "brooding": 1.4
    },
    "energyRange": [
      0.38,
      0.88
    ],
    "palette": [
      "#27221E",
      "#76654C",
      "#45382A",
      "#988366",
      "#C1A37C"
    ],
    "composition": "diagonal",
    "figurePresence": "tiny",
    "backgroundFit": 0.8,
    "crop": {
      "x": 0.48,
      "y": 0.52,
      "scale": 1.07
    },
    "curatorNote": "Ancient weather, sea, and scale; a softer sublime field than the mountain panoramas."
  },
  {
    "id": "sublime_terrain-met-10482",
    "bucket": "sublime_terrain",
    "title": "The Parthenon",
    "artist": "Frederic Edwin Church",
    "year": "1871",
    "source": "met",
    "sourceId": "10482",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/10482",
    "imagePath": "/artworks/sublime_terrain/met-10482-parthenon.jpg",
    "license": "Public Domain",
    "tags": [
      "ruins",
      "ancient stone",
      "gold light",
      "architecture",
      "terrain"
    ],
    "genreWeights": {
      "cinematic": 2.0,
      "orchestral": 1.8,
      "ambient electronic": 1.3
    },
    "moodWeights": {
      "glowing": 2.0,
      "mysterious": 1.8,
      "starlit": 1.2
    },
    "energyRange": [
      0.35,
      0.85
    ],
    "palette": [
      "#6C5638",
      "#4C351F",
      "#71705D",
      "#788271",
      "#BF9155"
    ],
    "composition": "center_mass",
    "figurePresence": "tiny",
    "backgroundFit": 0.7,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.08
    },
    "curatorNote": "A historical sublime rather than a wilderness sublime; useful for solemn, luminous cinematic pieces."
  },
  {
    "id": "sublime_terrain-met-12800",
    "bucket": "sublime_terrain",
    "title": "The Belated Party on Mansfield Mountain",
    "artist": "Jerome B. Thompson",
    "year": "1858",
    "source": "met",
    "sourceId": "12800",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/12800",
    "imagePath": "/artworks/sublime_terrain/met-12800-belated-party-mansfield-mountain.jpg",
    "license": "Public Domain",
    "tags": [
      "mountain",
      "vista",
      "figures",
      "sunset",
      "new england",
      "sublime"
    ],
    "genreWeights": {
      "cinematic": 2.0,
      "orchestral": 1.8,
      "folk": 1.5,
      "post-rock": 1.6
    },
    "moodWeights": {
      "nostalgic": 2.0,
      "serene": 1.8,
      "triumphant": 1.4
    },
    "energyRange": [
      0.3,
      0.72
    ],
    "palette": [
      "#362C28",
      "#D2C6BC",
      "#6A5B46",
      "#B7A99C",
      "#E3D5C2"
    ],
    "composition": "diagonal",
    "figurePresence": "ambient",
    "backgroundFit": 0.69,
    "crop": {
      "x": 0.54,
      "y": 0.5,
      "scale": 1.1
    },
    "curatorNote": "More human than the other sublime pieces; useful for songs with folk memory inside a large landscape."
  },
  {
    "id": "sublime_terrain-met-10497",
    "bucket": "sublime_terrain",
    "title": "View from Mount Holyoke, Northampton, Massachusetts, after a Thunderstorm—The Oxbow",
    "artist": "Thomas Cole",
    "year": "1836",
    "source": "met",
    "sourceId": "10497",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/10497",
    "imagePath": "/artworks/sublime_terrain/met-10497-oxbow.jpg",
    "license": "Public Domain",
    "tags": [
      "storm",
      "river",
      "wilderness",
      "scale",
      "american landscape",
      "sublime"
    ],
    "genreWeights": {
      "cinematic": 2.8,
      "orchestral": 2.5,
      "post-rock": 2.1
    },
    "moodWeights": {
      "triumphant": 1.8,
      "mysterious": 2.0,
      "brooding": 1.7
    },
    "energyRange": [
      0.45,
      0.95
    ],
    "palette": [
      "#A8A295",
      "#2E2711",
      "#817057",
      "#474125",
      "#5C4D30"
    ],
    "composition": "diagonal",
    "figurePresence": "tiny",
    "backgroundFit": 0.78,
    "crop": {
      "x": 0.52,
      "y": 0.48,
      "scale": 1.08
    },
    "curatorNote": "A weather-split terrain: huge enough for cinematic arcs without becoming a character portrait."
  },
  {
    "id": "tidal_mineral-manual-signac-venice-pink-cloud-1909",
    "bucket": "tidal_mineral",
    "title": "Venice, The Pink Cloud",
    "artist": "Paul Signac",
    "year": "1909",
    "source": "manual",
    "sourceId": "signac-venice-pink-cloud-1909",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Paul_Signac_-_Venice,_The_Pink_Cloud,_1909_-_Google_Art_Project.jpg",
    "imagePath": "/artworks/tidal_mineral/manual-signac-venice-pink-cloud-1909.jpg",
    "license": "Public Domain",
    "tags": [
      "venice",
      "water",
      "boats",
      "pointillism",
      "pink",
      "glowing"
    ],
    "genreWeights": {
      "bossa nova": 2.0,
      "surf rock": 1.6,
      "dub": 1.2,
      "breakbeat": 0.9,
      "dream pop": 1.5
    },
    "moodWeights": {
      "glowing": 2.8,
      "serene": 1.7,
      "playful": 1.4,
      "hypnotic": 1.1
    },
    "energyRange": [
      0.28,
      0.78
    ],
    "palette": [
      "#BFB9BB",
      "#D9CED1",
      "#7D8C9A",
      "#E2D7DA",
      "#E8E0E0"
    ],
    "composition": "allover",
    "figurePresence": "tiny",
    "backgroundFit": 0.82,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.05
    },
    "curatorNote": "A dotted field of water and warm air; bright enough for motion, still restrained as a sleeve."
  },
  {
    "id": "tidal_mineral-met-11126",
    "bucket": "tidal_mineral",
    "title": "Maine Coast",
    "artist": "Winslow Homer",
    "year": "1896",
    "source": "met",
    "sourceId": "11126",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11126",
    "imagePath": "/artworks/tidal_mineral/met-11126-maine-coast.jpg",
    "license": "Public Domain",
    "tags": [
      "sea",
      "rock",
      "coast",
      "mineral",
      "wind"
    ],
    "genreWeights": {
      "surf rock": 2.4,
      "dub": 1.8,
      "breakbeat": 1.8,
      "bossa nova": 1.2
    },
    "moodWeights": {
      "brooding": 1.8,
      "serene": 1.6,
      "hypnotic": 1.8
    },
    "energyRange": [
      0.35,
      0.88
    ],
    "palette": [
      "#17110F",
      "#6B6C63",
      "#4E4F47",
      "#7F7D71",
      "#9E9884"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.83,
    "crop": {
      "x": 0.5,
      "y": 0.53,
      "scale": 1.06
    },
    "curatorNote": "Rock, tide, and gray water without postcard warmth."
  },
  {
    "id": "tidal_mineral-met-11127",
    "bucket": "tidal_mineral",
    "title": "Moonlight, Wood Island Light",
    "artist": "Winslow Homer",
    "year": "1894",
    "source": "met",
    "sourceId": "11127",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11127",
    "imagePath": "/artworks/tidal_mineral/met-11127-moonlight-wood-island-light.jpg",
    "license": "Public Domain",
    "tags": [
      "moonlight",
      "sea",
      "coast",
      "nocturne",
      "light",
      "water"
    ],
    "genreWeights": {
      "dub": 2.0,
      "ambient electronic": 1.9,
      "surf rock": 1.5,
      "trip hop": 1.4
    },
    "moodWeights": {
      "starlit": 2.4,
      "serene": 2.0,
      "mysterious": 1.8,
      "brooding": 1.6
    },
    "energyRange": [
      0.18,
      0.68
    ],
    "palette": [
      "#3B3936",
      "#464743",
      "#20201F",
      "#585C54",
      "#89856F"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.88,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.05
    },
    "curatorNote": "A nocturne bridge between tidal mineral and night-city moods."
  },
  {
    "id": "tidal_mineral-met-11129",
    "bucket": "tidal_mineral",
    "title": "Natural Bridge, Bermuda",
    "artist": "Winslow Homer",
    "year": "1901",
    "source": "met",
    "sourceId": "11129",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11129",
    "imagePath": "/artworks/tidal_mineral/met-11129-natural-bridge-bermuda.jpg",
    "license": "Public Domain",
    "tags": [
      "watercolor",
      "bermuda",
      "rock",
      "coast",
      "mineral",
      "glowing"
    ],
    "genreWeights": {
      "surf rock": 2.6,
      "dub": 2.0,
      "bossa nova": 1.8,
      "breakbeat": 1.2
    },
    "moodWeights": {
      "glowing": 2.4,
      "serene": 1.9,
      "hypnotic": 1.4,
      "mysterious": 1.0
    },
    "energyRange": [
      0.32,
      0.82
    ],
    "palette": [
      "#55878D",
      "#BBB9A3",
      "#48585A",
      "#7B9995",
      "#EADEC3"
    ],
    "composition": "diagonal",
    "figurePresence": "none",
    "backgroundFit": 0.86,
    "crop": {
      "x": 0.48,
      "y": 0.56,
      "scale": 1.04
    },
    "curatorNote": "Rock, coast, watercolor force, and mineral water mood without beach-tourism softness."
  },
  {
    "id": "tidal_mineral-met-11130",
    "bucket": "tidal_mineral",
    "title": "Northeaster",
    "artist": "Winslow Homer",
    "year": "1895; reworked by 1901",
    "source": "met",
    "sourceId": "11130",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11130",
    "imagePath": "/artworks/tidal_mineral/met-11130-northeaster.jpg",
    "license": "Public Domain",
    "tags": [
      "sea",
      "rock",
      "surf",
      "foam",
      "storm",
      "mineral"
    ],
    "genreWeights": {
      "surf rock": 2.8,
      "breakbeat": 2.3,
      "dub": 1.7,
      "post-rock": 1.8
    },
    "moodWeights": {
      "brooding": 2.2,
      "hypnotic": 2.0,
      "mysterious": 1.7
    },
    "energyRange": [
      0.45,
      0.95
    ],
    "palette": [
      "#7B888D",
      "#1F272C",
      "#596B70",
      "#A0ADB2",
      "#C4CDD1"
    ],
    "composition": "diagonal",
    "figurePresence": "none",
    "backgroundFit": 0.8,
    "crop": {
      "x": 0.54,
      "y": 0.5,
      "scale": 1.08
    },
    "curatorNote": "Heavy surf and rock mass for high-pressure coastal rhythm."
  },
  {
    "id": "tidal_mineral-met-11138",
    "bucket": "tidal_mineral",
    "title": "Shore and Surf, Nassau",
    "artist": "Winslow Homer",
    "year": "1899",
    "source": "met",
    "sourceId": "11138",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11138",
    "imagePath": "/artworks/tidal_mineral/met-11138-shore-and-surf-nassau.jpg",
    "license": "Public Domain",
    "tags": [
      "watercolor",
      "shore",
      "surf",
      "glowing water",
      "rock"
    ],
    "genreWeights": {
      "bossa nova": 2.1,
      "dub": 1.8,
      "surf rock": 2.0,
      "afrobeat": 1.4
    },
    "moodWeights": {
      "glowing": 2.3,
      "serene": 1.8,
      "hypnotic": 1.7
    },
    "energyRange": [
      0.32,
      0.82
    ],
    "palette": [
      "#858E87",
      "#3D4344",
      "#616E6C",
      "#90A6A0",
      "#C4CBBF"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.86,
    "crop": {
      "x": 0.52,
      "y": 0.54,
      "scale": 1.05
    },
    "curatorNote": "Tropical water with mineral restraint; bright, but not vacation-coded."
  },
  {
    "id": "pastoral_memory-met-435988",
    "bucket": "pastoral_memory",
    "title": "Ville-d'Avray",
    "artist": "Camille Corot",
    "year": "1870",
    "source": "met",
    "sourceId": "435988",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/435988",
    "imagePath": "/artworks/pastoral_memory/met-435988-corot-ville-davray.jpg",
    "license": "Public Domain",
    "tags": [
      "barbizon",
      "pond",
      "trees",
      "pewter sky",
      "soft memory"
    ],
    "genreWeights": {
      "lo-fi": 2.2,
      "folk": 2.0,
      "dream pop": 1.8,
      "solo piano": 1.6
    },
    "moodWeights": {
      "nostalgic": 2.5,
      "melancholic": 1.8,
      "serene": 1.7
    },
    "energyRange": [
      0.12,
      0.6
    ],
    "palette": [
      "#444538",
      "#797B6D",
      "#292C21",
      "#333225",
      "#1A1A13"
    ],
    "composition": "center_mass",
    "figurePresence": "ambient",
    "backgroundFit": 0.79,
    "crop": {
      "x": 0.48,
      "y": 0.5,
      "scale": 1.08
    },
    "curatorNote": "A dim pond memory with enough branches and haze to hold a lo-fi sleeve."
  },
  {
    "id": "pastoral_memory-met-436083",
    "bucket": "pastoral_memory",
    "title": "A River Landscape with Storks",
    "artist": "Charles-François Daubigny",
    "year": "1864",
    "source": "met",
    "sourceId": "436083",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436083",
    "imagePath": "/artworks/pastoral_memory/met-436083-daubigny-river-landscape-with-storks.jpg",
    "license": "Public Domain",
    "tags": [
      "barbizon",
      "river",
      "storks",
      "trees",
      "soft green",
      "memory"
    ],
    "genreWeights": {
      "lo-fi": 2.0,
      "folk": 2.2,
      "dream pop": 1.4,
      "bluegrass": 1.3
    },
    "moodWeights": {
      "nostalgic": 2.2,
      "serene": 2.0,
      "cozy": 1.5
    },
    "energyRange": [
      0.12,
      0.62
    ],
    "palette": [
      "#938E71",
      "#25200F",
      "#1D1C0D",
      "#0F0C05",
      "#403B22"
    ],
    "composition": "low_horizon",
    "figurePresence": "tiny",
    "backgroundFit": 0.84,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.04
    },
    "curatorNote": "A soft green river field; the storks are rhythm, not subject."
  },
  {
    "id": "pastoral_memory-met-436081",
    "bucket": "pastoral_memory",
    "title": "Landscape on a River",
    "artist": "Charles-François Daubigny",
    "year": "1863",
    "source": "met",
    "sourceId": "436081",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436081",
    "imagePath": "/artworks/pastoral_memory/met-436081-daubigny-landscape-on-a-river.jpg",
    "license": "Public Domain",
    "tags": [
      "barbizon",
      "river",
      "village",
      "flat sky",
      "soft field"
    ],
    "genreWeights": {
      "lo-fi": 2.1,
      "folk": 2.0,
      "dream pop": 1.6,
      "bluegrass": 1.2
    },
    "moodWeights": {
      "nostalgic": 2.3,
      "serene": 1.9,
      "cozy": 1.4
    },
    "energyRange": [
      0.1,
      0.58
    ],
    "palette": [
      "#1F1C10",
      "#535039",
      "#7B7B66",
      "#9A9577",
      "#A9A27F"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.86,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.03
    },
    "curatorNote": "Old river weather: low drama, strong background usability."
  },
  {
    "id": "pastoral_memory-manual-monet-haystack-morning-snow-effect",
    "bucket": "pastoral_memory",
    "title": "Haystack, Morning Snow Effect",
    "artist": "Claude Monet",
    "year": "1891",
    "source": "manual",
    "sourceId": "monet-haystack-morning-snow-effect",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Claude_Monet,_Haystack,_Morning_Snow_Effect_(Meule,_Effet_de_Neige,_le_Matin),_1891,_oil_on_canvas,_65_x_92_cm,_Museum_of_Fine_Arts,_Boston.jpg",
    "imagePath": "/artworks/pastoral_memory/manual-monet-haystack-morning-snow-effect-1891.jpg",
    "license": "Public Domain",
    "tags": [
      "snow",
      "haystack",
      "morning",
      "field",
      "soft",
      "nostalgic"
    ],
    "genreWeights": {
      "lo-fi": 2.3,
      "folk": 1.8,
      "dream pop": 1.9,
      "solo piano": 1.3
    },
    "moodWeights": {
      "nostalgic": 2.6,
      "cozy": 1.8,
      "bittersweet": 1.7,
      "serene": 1.4
    },
    "energyRange": [
      0.18,
      0.64
    ],
    "palette": [
      "#73809D",
      "#A9A4AA",
      "#B8B3B8",
      "#58515D",
      "#C7C0C0"
    ],
    "composition": "center_mass",
    "figurePresence": "none",
    "backgroundFit": 0.8,
    "crop": {
      "x": 0.52,
      "y": 0.55,
      "scale": 1.05
    },
    "curatorNote": "Snow and grain reduced to a soft object-memory; good for quiet loops and pastoral haze."
  },
  {
    "id": "pastoral_memory-manual-rawpixel-2681194",
    "bucket": "pastoral_memory",
    "title": "Woman Lying in the Dunes near Noordwijk",
    "artist": "Jan Toorop",
    "year": "1902",
    "source": "manual",
    "sourceId": "rawpixel-2681194",
    "sourceUrl": "https://www.rawpixel.com/image/2681194/free-illustration-image-art-nouveau-woman-field",
    "imagePath": "/artworks/pastoral_memory/rawpixel-toorop-woman-lying-dunes-noordwijk-1902.jpg",
    "license": "Public Domain",
    "tags": [
      "dunes",
      "reclining",
      "field",
      "pale",
      "dream",
      "pastoral",
      "yellow green"
    ],
    "genreWeights": {
      "dream pop": 2.5,
      "lo-fi": 2.1,
      "bedroom": 1.7,
      "folk": 1.5
    },
    "moodWeights": {
      "dreamy": 2.8,
      "nostalgic": 1.9,
      "bittersweet": 1.6,
      "cozy": 1.2
    },
    "energyRange": [
      0.08,
      0.48
    ],
    "palette": [
      "#CCD09B",
      "#B9BF7E",
      "#D9DCAC",
      "#D5DDD4",
      "#E2E4D6"
    ],
    "composition": "horizontal_recline",
    "figurePresence": "ambient",
    "backgroundFit": 0.78,
    "crop": {
      "x": 0.52,
      "y": 0.54,
      "scale": 1.04
    },
    "curatorNote": "A body nearly dissolved into grass and pale air; intimate but not portrait-led."
  },
  {
    "id": "pastoral_memory-met-11897",
    "bucket": "pastoral_memory",
    "title": "Lake Squam from Red Hill",
    "artist": "William Trost Richards",
    "year": "1874",
    "source": "met",
    "sourceId": "11897",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11897",
    "imagePath": "/artworks/pastoral_memory/met-11897-lake-squam-from-red-hill.jpg",
    "license": "Public Domain",
    "tags": [
      "lake",
      "hill",
      "pastoral",
      "luminism",
      "memory",
      "green"
    ],
    "genreWeights": {
      "folk": 2.2,
      "lo-fi": 2.0,
      "dream pop": 1.5,
      "bluegrass": 1.7
    },
    "moodWeights": {
      "nostalgic": 2.5,
      "serene": 1.9,
      "cozy": 1.5,
      "bittersweet": 1.3
    },
    "energyRange": [
      0.16,
      0.62
    ],
    "palette": [
      "#81786C",
      "#A89C93",
      "#4E4434",
      "#B4AC9F",
      "#C8BB9E"
    ],
    "composition": "deep_perspective",
    "figurePresence": "none",
    "backgroundFit": 0.88,
    "crop": {
      "x": 0.5,
      "y": 0.54,
      "scale": 1.04
    },
    "curatorNote": "A lake remembered from a hill rather than visited; pastoral without postcard sweetness."
  },
  {
    "id": "nocturne_metro-commons-pissarro-boulevard-montmartre-at-night",
    "bucket": "nocturne_metro",
    "title": "The Boulevard Montmartre at Night",
    "artist": "Camille Pissarro",
    "year": "1897",
    "source": "commons",
    "sourceId": "pissarro-boulevard-montmartre-at-night",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Camille_Pissarro,_The_Boulevard_Montmartre_at_Night,_1897.jpg",
    "imagePath": "/artworks/nocturne_metro/commons-pissarro-boulevard-montmartre-at-night.jpg",
    "license": "Public Domain",
    "tags": [
      "night",
      "boulevard",
      "street lights",
      "crowd",
      "paris",
      "wet glow"
    ],
    "genreWeights": {
      "trip hop": 2.5,
      "deep house": 2.4,
      "city pop": 2.1,
      "garage": 1.6
    },
    "moodWeights": {
      "smoky": 2.5,
      "starlit": 2.1,
      "hypnotic": 1.9,
      "playful": 1.2
    },
    "energyRange": [
      0.42,
      0.88
    ],
    "palette": [
      "#302F3C",
      "#181C31",
      "#4B4443",
      "#71644F",
      "#958766"
    ],
    "composition": "allover",
    "figurePresence": "ambient",
    "backgroundFit": 0.86,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.07
    },
    "curatorNote": "Dense little lights and wet street motion; excellent for night-driving beats."
  },
  {
    "id": "nocturne_metro-commons-hassam-rainy-day-fifth-avenue",
    "bucket": "nocturne_metro",
    "title": "Rainy Day, Fifth Avenue",
    "artist": "Childe Hassam",
    "year": "1916",
    "source": "commons",
    "sourceId": "hassam-rainy-day-fifth-avenue",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Childe_Hassam_-_Rainy_Day,_Fifth_Avenue_-_y1942-62_-_Princeton_University_Art_Museum.jpg",
    "imagePath": "/artworks/nocturne_metro/commons-hassam-rainy-day-fifth-avenue.jpg",
    "license": "Public Domain",
    "tags": [
      "rain",
      "fifth avenue",
      "flags",
      "urban blur",
      "wet street",
      "blue red"
    ],
    "genreWeights": {
      "city pop": 2.2,
      "trip hop": 2.0,
      "deep house": 1.8,
      "lo-fi": 1.4
    },
    "moodWeights": {
      "smoky": 2.1,
      "nostalgic": 2.0,
      "melancholic": 1.7,
      "glowing": 1.3
    },
    "energyRange": [
      0.28,
      0.74
    ],
    "palette": [
      "#495259",
      "#2E2E33",
      "#687982",
      "#809EA6",
      "#A7C0BC"
    ],
    "composition": "diagonal",
    "figurePresence": "ambient",
    "backgroundFit": 0.79,
    "crop": {
      "x": 0.52,
      "y": 0.5,
      "scale": 1.1
    },
    "curatorNote": "Rain as blur and crowd texture; good for urban rain without literal window imagery."
  },
  {
    "id": "nocturne_metro-manual-monet-arrival-normandy-train",
    "bucket": "nocturne_metro",
    "title": "Arrival of the Normandy Train, Gare Saint-Lazare",
    "artist": "Claude Monet",
    "year": "1877",
    "source": "manual",
    "sourceId": "monet-arrival-normandy-train",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Arrival_of_the_Normandy_Train,_Gare_Saint-Lazare_-_Google_Art_Project.jpg",
    "imagePath": "/artworks/nocturne_metro/manual-monet-arrival-normandy-train-gare-saint-lazare-1877.jpg",
    "license": "Public Domain",
    "tags": [
      "train",
      "station",
      "smoke",
      "industrial",
      "blue green",
      "motion"
    ],
    "genreWeights": {
      "trip hop": 2.5,
      "deep house": 1.9,
      "garage": 1.7,
      "techno": 1.5
    },
    "moodWeights": {
      "smoky": 2.8,
      "brooding": 2.1,
      "hypnotic": 1.8,
      "mysterious": 1.4
    },
    "energyRange": [
      0.38,
      0.92
    ],
    "palette": [
      "#526B6D",
      "#3C4D53",
      "#6C8483",
      "#8A9FA1",
      "#B1BCBE"
    ],
    "composition": "center_mass",
    "figurePresence": "ambient",
    "backgroundFit": 0.86,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.08
    },
    "curatorNote": "Steam, roof geometry, and blurred crowd movement: rain-city music without literal rain."
  },
  {
    "id": "nocturne_metro-commons-cooper-broadway-from-post-office-wall-street",
    "bucket": "nocturne_metro",
    "title": "Broadway from the Post Office (Wall Street)",
    "artist": "Colin Campbell Cooper",
    "year": "ca. 1909",
    "source": "commons",
    "sourceId": "cooper-broadway-from-post-office-wall-street",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Colin_Campbell_Cooper,_Broadway_from_the_Post_Office_(Wall_Street).jpg",
    "imagePath": "/artworks/nocturne_metro/commons-cooper-broadway-from-post-office-wall-street.jpg",
    "license": "Public Domain",
    "tags": [
      "skyscraper",
      "wall street",
      "smoke",
      "city haze",
      "vertical",
      "crowd"
    ],
    "genreWeights": {
      "city pop": 2.4,
      "deep house": 1.8,
      "trip hop": 1.7,
      "synthwave": 1.4
    },
    "moodWeights": {
      "smoky": 2.4,
      "glowing": 1.8,
      "brooding": 1.7
    },
    "energyRange": [
      0.35,
      0.86
    ],
    "palette": [
      "#A9836C",
      "#C9BA98",
      "#4F5053",
      "#675857",
      "#846358"
    ],
    "composition": "center_mass",
    "figurePresence": "tiny",
    "backgroundFit": 0.82,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.08
    },
    "curatorNote": "A hazy urban canyon that extends the Wall Street screenshot seed into a truer metro bucket."
  },
  {
    "id": "nocturne_metro-commons-caillebotte-paris-street-rainy-day",
    "bucket": "nocturne_metro",
    "title": "Paris Street; Rainy Day",
    "artist": "Gustave Caillebotte",
    "year": "1877",
    "source": "commons",
    "sourceId": "caillebotte-paris-street-rainy-day",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gustave_Caillebotte_-_Paris_Street;_Rainy_Day_-_Google_Art_Project.jpg",
    "imagePath": "/artworks/nocturne_metro/commons-caillebotte-paris-street-rainy-day.jpg",
    "license": "Public Domain",
    "tags": [
      "rain",
      "wet street",
      "urban",
      "umbrella",
      "gray sky",
      "paris"
    ],
    "genreWeights": {
      "trip hop": 2.4,
      "city pop": 2.1,
      "deep house": 1.8,
      "lo-fi": 1.5
    },
    "moodWeights": {
      "smoky": 2.3,
      "melancholic": 2.1,
      "brooding": 1.8,
      "serene": 1.3
    },
    "energyRange": [
      0.28,
      0.78
    ],
    "palette": [
      "#ABA99F",
      "#454540",
      "#817D79",
      "#C4C4B7",
      "#E0DAC1"
    ],
    "composition": "diagonal",
    "figurePresence": "central",
    "backgroundFit": 0.62,
    "crop": {
      "x": 0.49,
      "y": 0.5,
      "scale": 1.12
    },
    "curatorNote": "Iconic and foreground-heavy, so treat as calibration / low-frequency pick rather than default."
  },
  {
    "id": "nocturne_metro-manual-caffi-eclipse-1842",
    "bucket": "nocturne_metro",
    "title": "Eclipse of the Sun in Venice, July 6, 1842",
    "artist": "Ippolito Caffi",
    "year": "1842",
    "source": "manual",
    "sourceId": "caffi-eclipse-1842",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ippolito_Caffi,_Eclisse_di_sole_alle_Fondamenta_Nove_(1842).jpg",
    "imagePath": "/artworks/nocturne_metro/manual-caffi-eclipse-sun-venice-1842.jpg",
    "license": "Public Domain",
    "tags": [
      "eclipse",
      "venice",
      "water",
      "nightlike",
      "crowd",
      "cosmic",
      "nocturne"
    ],
    "genreWeights": {
      "trip hop": 2.2,
      "deep house": 1.8,
      "ambient electronic": 2.1,
      "city pop": 1.4
    },
    "moodWeights": {
      "mysterious": 2.8,
      "starlit": 2.4,
      "brooding": 1.8,
      "serene": 1.1
    },
    "energyRange": [
      0.25,
      0.78
    ],
    "palette": [
      "#A5AEB8",
      "#232724",
      "#657E8B",
      "#475E66",
      "#3D4949"
    ],
    "composition": "diagonal",
    "figurePresence": "ambient",
    "backgroundFit": 0.9,
    "crop": {
      "x": 0.5,
      "y": 0.48,
      "scale": 1.06
    },
    "curatorNote": "A public cosmic hush: dark water, tiny figures, and a cut of impossible light."
  },
  {
    "id": "nocturne_metro-commons-whistler-nocturne-southampton-water",
    "bucket": "nocturne_metro",
    "title": "Nocturne: Blue and Gold—Southampton Water",
    "artist": "James McNeill Whistler",
    "year": "1872",
    "source": "commons",
    "sourceId": "whistler-nocturne-southampton-water",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:James_McNeill_Whistler_-_Nocturne-_Blue_and_Gold--Southampton_Water_-_Google_Art_Project.jpg",
    "imagePath": "/artworks/nocturne_metro/commons-whistler-nocturne-blue-and-gold-southampton-water.jpg",
    "license": "Public Domain",
    "tags": [
      "nocturne",
      "night",
      "water",
      "smoky",
      "blue green",
      "harbor"
    ],
    "genreWeights": {
      "trip hop": 2.6,
      "deep house": 2.1,
      "city pop": 1.6,
      "ambient electronic": 2.2
    },
    "moodWeights": {
      "smoky": 2.7,
      "brooding": 2.3,
      "starlit": 2.2,
      "serene": 1.7
    },
    "energyRange": [
      0.22,
      0.72
    ],
    "palette": [
      "#5B6252",
      "#626B5A",
      "#6A7361",
      "#535849",
      "#747D69"
    ],
    "composition": "low_horizon",
    "figurePresence": "none",
    "backgroundFit": 0.93,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.04
    },
    "curatorNote": "Wet blue-green silence for night drives, rain, and smoky beats."
  },
  {
    "id": "nocturne_metro-commons-grimshaw-boar-lane-leeds",
    "bucket": "nocturne_metro",
    "title": "Boar Lane, Leeds",
    "artist": "John Atkinson Grimshaw",
    "year": "c. 1881",
    "source": "commons",
    "sourceId": "grimshaw-boar-lane-leeds",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:John_Atkinson_Grimshaw_(1836-1893)_-_Boar_Lane,_Leeds_-_LEEAG.PA.2000.0017_-_Leeds_Art_Gallery.jpg",
    "imagePath": "/artworks/nocturne_metro/commons-grimshaw-boar-lane-leeds.jpg",
    "license": "Public Domain",
    "tags": [
      "gaslight",
      "moon",
      "night",
      "wet city",
      "leeds",
      "smoke"
    ],
    "genreWeights": {
      "trip hop": 2.4,
      "deep house": 2.2,
      "city pop": 1.8,
      "ambient electronic": 1.4
    },
    "moodWeights": {
      "smoky": 2.7,
      "brooding": 2.3,
      "starlit": 2.0,
      "mysterious": 1.8
    },
    "energyRange": [
      0.25,
      0.78
    ],
    "palette": [
      "#768963",
      "#080A08",
      "#4F4630",
      "#251F19",
      "#141612"
    ],
    "composition": "low_horizon",
    "figurePresence": "ambient",
    "backgroundFit": 0.88,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.04
    },
    "curatorNote": "Small source image, but the gaslight atmosphere is very on-brief for nocturne metro."
  },
  {
    "id": "printed_signal-met-78790",
    "bucket": "printed_signal",
    "title": "A Realistic Sketchbook by Hokusai (Hokusai shashin gafu)",
    "artist": "Katsushika Hokusai",
    "year": "1814",
    "source": "met",
    "sourceId": "78790",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/78790",
    "imagePath": "/artworks/printed_signal/met-78790-hokusai-shashin-gafu.jpg",
    "license": "Public Domain",
    "tags": [
      "woodblock",
      "japan",
      "line",
      "sketchbook",
      "archive",
      "signal"
    ],
    "genreWeights": {
      "koto": 2.8,
      "guzheng": 2.1,
      "gamelan": 1.7,
      "minimal techno": 1.7,
      "baroque": 1.0
    },
    "moodWeights": {
      "mysterious": 2.2,
      "serene": 1.8,
      "brooding": 1.2,
      "hypnotic": 1.5
    },
    "energyRange": [
      0.12,
      0.7
    ],
    "palette": [
      "#CABDA4",
      "#DED0B7",
      "#998F7D",
      "#EDDDC3",
      "#DEDEDA"
    ],
    "composition": "allover",
    "figurePresence": "none",
    "backgroundFit": 0.82,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.04
    },
    "curatorNote": "A signal from an old image system: line, archive, restraint, and hand-made rhythm."
  },
  {
    "id": "printed_signal-met-49941",
    "bucket": "printed_signal",
    "title": "Pines and Waves at Ryūtō",
    "artist": "Katsushika Hokusai",
    "year": "ca. 1832",
    "source": "met",
    "sourceId": "49941",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/49941",
    "imagePath": "/artworks/printed_signal/met-49941-hokusai-pines-and-waves-ryuto.jpg",
    "license": "Public Domain",
    "tags": [
      "ukiyo-e",
      "waves",
      "pines",
      "linework",
      "archive",
      "water"
    ],
    "genreWeights": {
      "koto": 2.6,
      "guzheng": 2.2,
      "gamelan": 1.5,
      "minimal techno": 1.7
    },
    "moodWeights": {
      "serene": 2.0,
      "mysterious": 1.9,
      "hypnotic": 1.8
    },
    "energyRange": [
      0.2,
      0.72
    ],
    "palette": [
      "#CFCDB5",
      "#5A6973",
      "#AEAA97",
      "#EFDBBC",
      "#FBECD1"
    ],
    "composition": "diagonal",
    "figurePresence": "tiny",
    "backgroundFit": 0.82,
    "crop": {
      "x": 0.5,
      "y": 0.53,
      "scale": 1.07
    },
    "curatorNote": "Wave-line intelligence: musical, archival, and not too literal."
  },
  {
    "id": "printed_signal-met-54095",
    "bucket": "printed_signal",
    "title": "The Common Marigold and The Rajoman Flowers",
    "artist": "Kubo Shunman",
    "year": "19th century",
    "source": "met",
    "sourceId": "54095",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/54095",
    "imagePath": "/artworks/printed_signal/met-54095-kubo-shunman-common-marigold-rajoman-flowers.jpg",
    "license": "Public Domain",
    "tags": [
      "surimono",
      "flowers",
      "botanical",
      "linework",
      "symbol",
      "archive"
    ],
    "genreWeights": {
      "koto": 2.4,
      "guzheng": 2.2,
      "music box": 1.5,
      "minimal techno": 1.3
    },
    "moodWeights": {
      "serene": 2.3,
      "weightless": 1.7,
      "cozy": 1.4
    },
    "energyRange": [
      0.05,
      0.5
    ],
    "palette": [
      "#DCCFC4",
      "#A59B83",
      "#CEC1B0",
      "#E1D3C7",
      "#E4D6CA"
    ],
    "composition": "allover",
    "figurePresence": "none",
    "backgroundFit": 0.88,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.04
    },
    "curatorNote": "A botanical print that reads as delicate notation rather than illustration."
  },
  {
    "id": "printed_signal-met-55433",
    "bucket": "printed_signal",
    "title": "Sudden Shower over Shin-Ōhashi Bridge and Atake",
    "artist": "Utagawa Hiroshige",
    "year": "1857",
    "source": "met",
    "sourceId": "55433",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/55433",
    "imagePath": "/artworks/printed_signal/met-55433-hiroshige-sudden-shower.jpg",
    "license": "Public Domain",
    "tags": [
      "ukiyo-e",
      "rain",
      "bridge",
      "diagonal lines",
      "city rain",
      "print"
    ],
    "genreWeights": {
      "koto": 2.2,
      "guzheng": 1.8,
      "minimal techno": 2.0,
      "breakbeat": 1.5
    },
    "moodWeights": {
      "hypnotic": 2.3,
      "mysterious": 1.9,
      "brooding": 1.8
    },
    "energyRange": [
      0.35,
      0.82
    ],
    "palette": [
      "#8F8F85",
      "#A8AD98",
      "#645B5A",
      "#EDD0AA",
      "#FBE7CB"
    ],
    "composition": "diagonal",
    "figurePresence": "ambient",
    "backgroundFit": 0.84,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.08
    },
    "curatorNote": "Rain as a graphic system: perfect for line, pulse, and wet-city translation."
  },
  {
    "id": "printed_signal-met-45321",
    "bucket": "printed_signal",
    "title": "View of the Asakusa Kinryūzan Temple from the Azuma Bridge in the Rain",
    "artist": "Utagawa Hiroshige",
    "year": "ca. 1840",
    "source": "met",
    "sourceId": "45321",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/45321",
    "imagePath": "/artworks/printed_signal/met-45321-hiroshige-asakusa-bridge-rain.jpg",
    "license": "Public Domain",
    "tags": [
      "ukiyo-e",
      "rain",
      "bridge",
      "temple",
      "vertical print",
      "signal"
    ],
    "genreWeights": {
      "koto": 2.4,
      "guzheng": 2.0,
      "minimal techno": 1.8,
      "ambient": 1.3
    },
    "moodWeights": {
      "serene": 2.0,
      "mysterious": 1.8,
      "melancholic": 1.7
    },
    "energyRange": [
      0.2,
      0.68
    ],
    "palette": [
      "#A9AC9D",
      "#6C5E5B",
      "#A19385",
      "#FDF0D9",
      "#B7B9A5"
    ],
    "composition": "diagonal",
    "figurePresence": "ambient",
    "backgroundFit": 0.78,
    "crop": {
      "x": 0.52,
      "y": 0.5,
      "scale": 1.1
    },
    "curatorNote": "A narrow rain print with enough symbolic weather to support softer rain tracks."
  },
  {
    "id": "stage_heat-manual-canaletto-piazza-san-marco",
    "bucket": "stage_heat",
    "title": "The Piazza San Marco in Venice",
    "artist": "Canaletto",
    "year": "1723–1724",
    "source": "manual",
    "sourceId": "canaletto-piazza-san-marco",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Canaletto_-_The_Piazza_San_Marco_in_Venice_-_Google_Art_Project.jpg",
    "imagePath": "/artworks/stage_heat/manual-canaletto-piazza-san-marco-venice.jpg",
    "license": "Public Domain",
    "tags": [
      "piazza",
      "venice",
      "public space",
      "architecture",
      "crowd",
      "sun"
    ],
    "genreWeights": {
      "swing": 2.0,
      "disco": 1.6,
      "funk": 1.4,
      "party": 1.5
    },
    "moodWeights": {
      "playful": 2.0,
      "euphoric": 1.4,
      "glowing": 1.6,
      "serene": 0.8
    },
    "energyRange": [
      0.35,
      0.85
    ],
    "palette": [
      "#33342C",
      "#8B9488",
      "#666857",
      "#ACAB98",
      "#C0BFAF"
    ],
    "composition": "deep_perspective",
    "figurePresence": "ambient",
    "backgroundFit": 0.74,
    "crop": {
      "x": 0.5,
      "y": 0.55,
      "scale": 1.08
    },
    "curatorNote": "Public rhythm without a modern club signal: plaza, shadow, tiny figures, warm civic tempo."
  },
  {
    "id": "stage_heat-manual-cooper-view-wall-street",
    "bucket": "stage_heat",
    "title": "View of Wall Street",
    "artist": "Colin Campbell Cooper",
    "year": "early 20th century",
    "source": "manual",
    "sourceId": "cooper-view-wall-street",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Olin_campbell_cooper_view_of_wall_street022728).jpg",
    "imagePath": "/artworks/stage_heat/manual-cooper-view-of-wall-street.jpg",
    "license": "Public Domain",
    "tags": [
      "city",
      "wall street",
      "skyscraper",
      "impressionism",
      "daylight",
      "urban rhythm"
    ],
    "genreWeights": {
      "city pop": 2.3,
      "disco": 1.4,
      "funk": 1.2,
      "deep house": 1.4
    },
    "moodWeights": {
      "glowing": 2.4,
      "playful": 1.4,
      "euphoric": 1.2,
      "starlit": 0.6
    },
    "energyRange": [
      0.42,
      0.9
    ],
    "palette": [
      "#85A39E",
      "#7F8F87",
      "#ABA584",
      "#686A6A",
      "#BDB995"
    ],
    "composition": "vertical_city",
    "figurePresence": "tiny",
    "backgroundFit": 0.76,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.08
    },
    "curatorNote": "A bright city field with soft vertical pressure; useful for public rhythm without party clichés."
  },
  {
    "id": "stage_heat-commons-degas-rehearsal-ballet-onstage",
    "bucket": "stage_heat",
    "title": "The Rehearsal of the Ballet Onstage",
    "artist": "Edgar Degas",
    "year": "ca. 1874",
    "source": "commons",
    "sourceId": "degas-rehearsal-ballet-onstage",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Rehearsal_of_the_Ballet_Onstage_MET_DT1565.jpg",
    "imagePath": "/artworks/stage_heat/commons-degas-rehearsal-ballet-onstage.jpg",
    "license": "Public Domain",
    "tags": [
      "stage",
      "ballet",
      "rehearsal",
      "public rhythm",
      "warm light"
    ],
    "genreWeights": {
      "swing": 2.0,
      "disco": 1.4,
      "funk": 1.5,
      "bedroom": 1.0
    },
    "moodWeights": {
      "playful": 1.8,
      "nostalgic": 1.8,
      "cozy": 1.2
    },
    "energyRange": [
      0.3,
      0.78
    ],
    "palette": [
      "#716748",
      "#A4946F",
      "#2F2B21",
      "#454534",
      "#5F4E32"
    ],
    "composition": "diagonal",
    "figurePresence": "ambient",
    "backgroundFit": 0.78,
    "crop": {
      "x": 0.52,
      "y": 0.5,
      "scale": 1.07
    },
    "curatorNote": "Stage energy softened into rehearsal: movement, but still background-friendly."
  },
  {
    "id": "stage_heat-commons-seurat-grande-jatte-1884",
    "bucket": "stage_heat",
    "title": "A Sunday on La Grande Jatte",
    "artist": "Georges Seurat",
    "year": "1884",
    "source": "commons",
    "sourceId": "seurat-grande-jatte-1884",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg",
    "imagePath": "/artworks/stage_heat/commons-seurat-sunday-grande-jatte-1884.jpg",
    "license": "Public Domain",
    "tags": [
      "pointillism",
      "crowd",
      "park",
      "public rhythm",
      "stage heat"
    ],
    "genreWeights": {
      "disco": 1.9,
      "funk": 1.7,
      "swing": 1.8,
      "party": 1.5
    },
    "moodWeights": {
      "playful": 2.0,
      "euphoric": 1.5,
      "serene": 1.4
    },
    "energyRange": [
      0.38,
      0.85
    ],
    "palette": [
      "#294333",
      "#BDBC96",
      "#87866E",
      "#63625C",
      "#554554"
    ],
    "composition": "allover",
    "figurePresence": "ambient",
    "backgroundFit": 0.68,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.06
    },
    "curatorNote": "A known calibration piece for public rhythm; useful, but not the taste anchor."
  },
  {
    "id": "stage_heat-commons-toulouse-lautrec-moulin-rouge-dance",
    "bucket": "stage_heat",
    "title": "At the Moulin Rouge: The Dance",
    "artist": "Henri de Toulouse-Lautrec",
    "year": "1889–90",
    "source": "commons",
    "sourceId": "toulouse-lautrec-moulin-rouge-dance",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Henri_de_Toulouse-Lautrec,_French_-_At_the_Moulin_Rouge-_The_Dance_-_Google_Art_Project.jpg",
    "imagePath": "/artworks/stage_heat/commons-toulouse-lautrec-moulin-rouge-dance.jpg",
    "license": "Public Domain",
    "tags": [
      "dance",
      "cabaret",
      "crowd",
      "stage",
      "warm interior",
      "public rhythm"
    ],
    "genreWeights": {
      "disco": 2.3,
      "funk": 2.1,
      "swing": 2.4,
      "garage": 1.4
    },
    "moodWeights": {
      "playful": 2.3,
      "euphoric": 2.0,
      "smoky": 1.5
    },
    "energyRange": [
      0.45,
      0.95
    ],
    "palette": [
      "#3D442A",
      "#887E4E",
      "#6B5C37",
      "#D9A282",
      "#999260"
    ],
    "composition": "center_mass",
    "figurePresence": "ambient",
    "backgroundFit": 0.74,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.08
    },
    "curatorNote": "Human rhythm without modern party cliché; a stage-image with real heat."
  },
  {
    "id": "interior_reverie-met-459086",
    "bucket": "interior_reverie",
    "title": "Leisure Time in an Elegant Setting",
    "artist": "Pieter de Hooch",
    "year": "ca. 1663–65",
    "source": "met",
    "sourceId": "459086",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/459086",
    "imagePath": "/artworks/interior_reverie/met-459086-leisure-time-in-an-elegant-setting.jpg",
    "license": "Public Domain",
    "tags": [
      "interior",
      "room",
      "domestic",
      "window light",
      "quiet figures"
    ],
    "genreWeights": {
      "bedroom": 2.0,
      "lullaby": 1.6,
      "neo-soul": 1.5,
      "solo piano": 1.7
    },
    "moodWeights": {
      "cozy": 2.2,
      "serene": 1.8,
      "nostalgic": 1.8
    },
    "energyRange": [
      0.18,
      0.65
    ],
    "palette": [
      "#241A10",
      "#110F0B",
      "#312313",
      "#3C2C19",
      "#524A38"
    ],
    "composition": "interior_depth",
    "figurePresence": "ambient",
    "backgroundFit": 0.72,
    "crop": {
      "x": 0.5,
      "y": 0.53,
      "scale": 1.08
    },
    "curatorNote": "A quiet interior grid; figures are present, but the room is the real rhythm."
  },
  {
    "id": "interior_reverie-met-436676",
    "bucket": "interior_reverie",
    "title": "Woman with a Water Pitcher, and a Man by a Bed",
    "artist": "Pieter de Hooch",
    "year": "ca. 1667–70",
    "source": "met",
    "sourceId": "436676",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/436676",
    "imagePath": "/artworks/interior_reverie/met-436676-woman-water-pitcher-man-by-bed.jpg",
    "license": "Public Domain",
    "tags": [
      "interior",
      "bed",
      "doorway",
      "domestic space",
      "warm shadow"
    ],
    "genreWeights": {
      "bedroom": 2.0,
      "neo-soul": 1.5,
      "solo piano": 1.5,
      "lullaby": 1.4
    },
    "moodWeights": {
      "cozy": 1.9,
      "nostalgic": 1.8,
      "serene": 1.4
    },
    "energyRange": [
      0.15,
      0.62
    ],
    "palette": [
      "#301B0F",
      "#1B1410",
      "#3C2513",
      "#432E19",
      "#5D4828"
    ],
    "composition": "interior_depth",
    "figurePresence": "ambient",
    "backgroundFit": 0.7,
    "crop": {
      "x": 0.52,
      "y": 0.5,
      "scale": 1.1
    },
    "curatorNote": "A domestic threshold image; usable when cropped as space rather than story."
  },
  {
    "id": "interior_reverie-manual-granfelt-reposing-dog-1894",
    "bucket": "interior_reverie",
    "title": "Reposing Dog",
    "artist": "Sigrid Granfelt",
    "year": "1894",
    "source": "manual",
    "sourceId": "granfelt-reposing-dog-1894",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sigrid_Granfelt_-_Reposing_Dog_-_A_III_2492_-_Finnish_National_Gallery.jpg",
    "imagePath": "/artworks/interior_reverie/manual-granfelt-reposing-dog-1894.jpg",
    "license": "CC0",
    "tags": [
      "dog",
      "rest",
      "interior",
      "quiet",
      "sleep",
      "cream",
      "brown"
    ],
    "genreWeights": {
      "bedroom": 2.6,
      "lullaby": 2.3,
      "neo-soul": 1.3,
      "lo-fi": 2.1
    },
    "moodWeights": {
      "cozy": 2.8,
      "serene": 2.2,
      "nostalgic": 1.2,
      "bittersweet": 0.8
    },
    "energyRange": [
      0.05,
      0.45
    ],
    "palette": [
      "#181815",
      "#42372C",
      "#7A664D",
      "#CBC3B1",
      "#AFA189"
    ],
    "composition": "diagonal",
    "figurePresence": "central_animal",
    "backgroundFit": 0.7,
    "crop": {
      "x": 0.52,
      "y": 0.5,
      "scale": 1.04
    },
    "curatorNote": "A private, almost silent image; useful when Murmur needs warmth without human portrait energy."
  },
  {
    "id": "interior_reverie-met-441933",
    "bucket": "interior_reverie",
    "title": "Moonlight, Strandgade 30",
    "artist": "Vilhelm Hammershøi",
    "year": "1900–1906",
    "source": "met",
    "sourceId": "441933",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/441933",
    "imagePath": "/artworks/interior_reverie/met-441933-moonlight-strandgade-30.jpg",
    "license": "Public Domain",
    "tags": [
      "interior",
      "moonlight",
      "empty room",
      "window",
      "hush"
    ],
    "genreWeights": {
      "bedroom": 2.6,
      "lullaby": 2.2,
      "solo piano": 2.1,
      "ambient": 2.5
    },
    "moodWeights": {
      "serene": 2.8,
      "melancholic": 2.3,
      "weightless": 2.0,
      "cozy": 1.4
    },
    "energyRange": [
      0.05,
      0.48
    ],
    "palette": [
      "#624E47",
      "#867067",
      "#3C2D29",
      "#55413A",
      "#4B3B34"
    ],
    "composition": "interior_depth",
    "figurePresence": "none",
    "backgroundFit": 0.96,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.03
    },
    "curatorNote": "Probably the cleanest interior field in this batch: pure room, pale moon, no narrative drag."
  },
  {
    "id": "hypermodern_void-commons-anna-atkins-algae-cyanotype",
    "bucket": "hypermodern_void",
    "title": "Dictyota dichotoma, in the young state; and in fruit",
    "artist": "Anna Atkins",
    "year": "1843–53",
    "source": "commons",
    "sourceId": "anna-atkins-algae-cyanotype",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anna_Atkins_algae_cyanotype.jpg",
    "imagePath": "/artworks/hypermodern_void/commons-anna-atkins-algae-cyanotype.jpg",
    "license": "Public Domain",
    "tags": [
      "cyanotype",
      "algae",
      "blueprint",
      "botanical signal",
      "science archive"
    ],
    "genreWeights": {
      "ambient electronic": 2.4,
      "minimal techno": 1.8,
      "synthwave": 1.6,
      "music box": 1.2
    },
    "moodWeights": {
      "weightless": 2.2,
      "serene": 2.0,
      "starlit": 1.8,
      "mysterious": 1.5
    },
    "energyRange": [
      0.05,
      0.58
    ],
    "palette": [
      "#083883",
      "#8AB4E0",
      "#113A82",
      "#235096",
      "#0C2E6F"
    ],
    "composition": "allover",
    "figurePresence": "none",
    "backgroundFit": 0.9,
    "crop": {
      "x": 0.5,
      "y": 0.52,
      "scale": 1.06
    },
    "curatorNote": "A clean blue scientific ghost: excellent for quiet future-facing sleeves."
  },
  {
    "id": "hypermodern_void-commons-haeckel-discomedusae-8",
    "bucket": "hypermodern_void",
    "title": "Discomedusae, plate 8 from Kunstformen der Natur",
    "artist": "Ernst Haeckel",
    "year": "1904",
    "source": "commons",
    "sourceId": "haeckel-discomedusae-8",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Haeckel_Discomedusae_8.jpg",
    "imagePath": "/artworks/hypermodern_void/commons-haeckel-discomedusae-8.jpg",
    "license": "Public Domain",
    "tags": [
      "scientific plate",
      "marine",
      "organic geometry",
      "signal",
      "future nature"
    ],
    "genreWeights": {
      "minimal techno": 2.2,
      "ambient electronic": 2.0,
      "gamelan": 1.4,
      "synthwave": 1.5
    },
    "moodWeights": {
      "hypnotic": 2.5,
      "mysterious": 1.9,
      "glowing": 1.7
    },
    "energyRange": [
      0.25,
      0.85
    ],
    "palette": [
      "#A4918D",
      "#FEFEFE",
      "#774743",
      "#DED2CA",
      "#FDFEFD"
    ],
    "composition": "allover",
    "figurePresence": "none",
    "backgroundFit": 0.76,
    "crop": {
      "x": 0.5,
      "y": 0.5,
      "scale": 1.1
    },
    "curatorNote": "A biological signal field: ornate enough for motion, archival enough for Murmur."
  },
  {
    "id": "hypermodern_void-commons-whistler-nocturne-black-gold-falling-rocket",
    "bucket": "hypermodern_void",
    "title": "Nocturne in Black and Gold: The Falling Rocket",
    "artist": "James McNeill Whistler",
    "year": "1875",
    "source": "commons",
    "sourceId": "whistler-nocturne-black-gold-falling-rocket",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Whistler-Nocturne_in_black_and_gold.jpg",
    "imagePath": "/artworks/hypermodern_void/commons-whistler-nocturne-black-gold-falling-rocket.jpg",
    "license": "Public Domain",
    "tags": [
      "nocturne",
      "fireworks",
      "dark field",
      "abstraction",
      "smoke",
      "signal"
    ],
    "genreWeights": {
      "ambient electronic": 2.7,
      "minimal techno": 2.4,
      "synthwave": 2.1,
      "trip hop": 1.8
    },
    "moodWeights": {
      "mysterious": 2.8,
      "brooding": 2.4,
      "starlit": 2.2,
      "hypnotic": 2.0
    },
    "energyRange": [
      0.2,
      0.82
    ],
    "palette": [
      "#314036",
      "#152219",
      "#243329",
      "#3E4D3D",
      "#646740"
    ],
    "composition": "allover",
    "figurePresence": "none",
    "backgroundFit": 0.92,
    "crop": {
      "x": 0.5,
      "y": 0.48,
      "scale": 1.06
    },
    "curatorNote": "Almost a dark signal field: historical, but it behaves like an abstract future background."
  },
  {
    "id": "hypermodern_void-commons-redon-eye-like-a-strange-balloon",
    "bucket": "hypermodern_void",
    "title": "To Edgar Poe (The Eye, Like a Strange Balloon, Mounts toward Infinity)",
    "artist": "Odilon Redon",
    "year": "1882",
    "source": "commons",
    "sourceId": "redon-eye-like-a-strange-balloon",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:To_Edgar_Poe_(The_Eye,_Like_a_Strange_Balloon,_Mounts_toward_Infinity)_(A_Edgar_Poe_(L%27oeil,_comme_un_ballon_bizarre_se_dirige_vers_l%27infini))_LACMA_AC1997.14.1.1.jpg",
    "imagePath": "/artworks/hypermodern_void/commons-redon-eye-like-a-strange-balloon.jpg",
    "license": "Public Domain",
    "tags": [
      "symbolist",
      "void",
      "balloon",
      "eye",
      "noir",
      "cosmic"
    ],
    "genreWeights": {
      "synthwave": 2.2,
      "ambient electronic": 2.5,
      "minimal techno": 2.0,
      "vaporwave": 1.5
    },
    "moodWeights": {
      "mysterious": 2.8,
      "starlit": 2.0,
      "brooding": 2.2,
      "weightless": 1.7
    },
    "energyRange": [
      0.18,
      0.82
    ],
    "palette": [
      "#C0BCAA",
      "#4B473D",
      "#FAF8F1",
      "#EBE7D8",
      "#F3F0E4"
    ],
    "composition": "center_mass",
    "figurePresence": "none",
    "backgroundFit": 0.82,
    "crop": {
      "x": 0.5,
      "y": 0.45,
      "scale": 1.12
    },
    "curatorNote": "A proto-cosmic image: not modern in date, but modern in psychological space."
  }
] as const satisfies readonly MurmurArtwork[];

function hashToUnit(seed: string): number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return ((h >>> 0) % 1000000) / 1000000;
}

function inEnergyRange(energy: number | undefined, range: readonly [number, number]) {
  if (energy == null) return true;
  return energy >= range[0] && energy <= range[1];
}

function weightFor(value: string | undefined, weights: Record<string, number>) {
  if (!value) return 0;
  return weights[value] ?? weights[value.toLowerCase()] ?? 0;
}

function tagScore(song: SongVisualFacets, artwork: MurmurArtwork) {
  const terms = [song.scene, song.instrument, ...(song.tags ?? [])]
    .filter(Boolean)
    .map((x) => String(x).toLowerCase());
  if (!terms.length) return 0;
  const artTags = artwork.tags.map((x) => x.toLowerCase());
  return terms.reduce((sum, term) => sum + (artTags.includes(term) ? 0.8 : 0), 0);
}

function resolveBucket(song: SongVisualFacets): ArtworkBucket | undefined {
  const genre = song.genre?.toLowerCase();
  const mood = song.mood?.toLowerCase();
  const scene = song.scene?.toLowerCase();
  const energy = song.energy ?? 0.5;

  if (scene === "rain" && ["trip hop", "deep house", "city pop", "garage", "synthwave"].includes(genre ?? "")) return "nocturne_metro";
  if (scene === "rain" && energy < 0.42) return "interior_reverie";
  if (["koto", "guzheng", "gamelan"].includes(song.instrument?.toLowerCase() ?? "")) return "printed_signal";
  if (["techno", "minimal techno", "synthwave", "vaporwave", "ambient electronic"].includes(genre ?? "")) return "hypermodern_void";
  if (["cinematic", "orchestral", "post-rock"].includes(genre ?? "")) return "sublime_terrain";
  if (["surf rock", "dub", "bossa nova", "breakbeat"].includes(genre ?? "")) return "tidal_mineral";
  if (["lo-fi", "folk", "dream pop", "bedroom"].includes(genre ?? "")) return "pastoral_memory";
  if (["disco", "funk", "swing"].includes(genre ?? "") || mood === "euphoric" || mood === "playful") return "stage_heat";
  if (["ambient", "solo piano", "music box"].includes(genre ?? "") || mood === "serene" || mood === "weightless") return "luminist_air";
  return undefined;
}

export function scoreArtwork(song: SongVisualFacets, artwork: MurmurArtwork): number {
  if (!inEnergyRange(song.energy, artwork.energyRange)) return -Infinity;
  const bucket = resolveBucket(song);
  const bucketScore = bucket && artwork.bucket === bucket ? 3 : 0;
  const genreScore = weightFor(song.genre, artwork.genreWeights);
  const moodScore = weightFor(song.mood, artwork.moodWeights);
  const sceneTagScore = tagScore(song, artwork);
  const friendliness = artwork.backgroundFit;
  return bucketScore + genreScore + moodScore + sceneTagScore + friendliness;
}

export function selectArtwork(song: SongVisualFacets, artworks = MURMUR_ARTWORKS): MurmurArtwork {
  const scored = artworks
    .map((artwork) => ({ artwork, score: scoreArtwork(song, artwork as MurmurArtwork) }))
    .filter((x) => Number.isFinite(x.score))
    .sort((a, b) => b.score - a.score);
  const top = scored.slice(0, Math.min(8, scored.length));
  if (!top.length) return artworks[0] as MurmurArtwork;
  const idx = Math.floor(hashToUnit(song.id) * top.length);
  return top[idx].artwork as MurmurArtwork;
}
