import type { ArtworkCatalogEntry } from "./types";

const sharedMoodWeights = {
  dreamy: 0.4,
  melancholic: 0.4,
  mysterious: 0.3,
  serene: 0.4,
} as const;

export const ARTWORK_CATALOG = [
  {
    id: "luminist_air-met-11307",
    bucket: "luminist_air",
    title: "Eaton's Neck, Long Island",
    artist: "John Frederick Kensett",
    year: "1872",
    source: "met",
    sourceId: "11307",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/11307",
    imagePath: "/artworks/luminist_air/met-11307-eatons-neck-long-island.jpg",
    license: "Public Domain",
    tags: ["luminism", "coast", "stillness", "water", "serene", "ambient electronic", "solo piano"],
    genreWeights: {
      "ambient electronic": 2.4,
      "solo piano": 2.2,
      "music box lullaby": 1.9,
      "guzheng meditation": 1.7,
    },
    moodWeights: { ...sharedMoodWeights, serene: 2.6, melancholic: 1.9, weightless: 2 },
    energyRange: [0.2, 0.58],
    crop: { x: 0.48, y: 0.5, scale: 1.06 },
    curatorNote: "Low horizon and empty air for quiet, slow songs.",
  },
  {
    id: "pastoral_memory-met-11897",
    bucket: "pastoral_memory",
    title: "Lake Squam from Red Hill",
    artist: "William Trost Richards",
    year: "1874",
    source: "met",
    sourceId: "11897",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/11897",
    imagePath: "/artworks/pastoral_memory/met-11897-lake-squam-from-red-hill.jpg",
    license: "Public Domain",
    tags: ["lake", "pastoral", "memory", "landscape", "nostalgic", "cozy", "dream pop instrumental"],
    genreWeights: {
      "lo-fi hip hop": 1.8,
      "dream pop instrumental": 2.2,
      "celtic folk": 1.8,
      bluegrass: 1.8,
      chillwave: 1.2,
    },
    moodWeights: { nostalgic: 2.6, cozy: 2.2, bittersweet: 2, dreamy: 1.5 },
    energyRange: [0.25, 0.68],
    crop: { x: 0.5, y: 0.48, scale: 1.04 },
    curatorNote: "A remembered landscape for warm, private, acoustic or lo-fi songs.",
  },
  {
    id: "tidal_mineral-met-11129",
    bucket: "tidal_mineral",
    title: "Natural Bridge, Bermuda",
    artist: "Winslow Homer",
    year: "ca. 1901",
    source: "met",
    sourceId: "11129",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/11129",
    imagePath: "/artworks/tidal_mineral/met-11129-natural-bridge-bermuda.jpg",
    license: "Public Domain",
    tags: ["watercolor", "coast", "rock", "bermuda", "glowing", "surf rock", "bossa nova"],
    genreWeights: {
      "surf rock": 2.6,
      "reggae dub": 2,
      "bossa nova": 1.9,
      afrobeat: 1.4,
      "drum and bass": 0.8,
    },
    moodWeights: { glowing: 2.2, hypnotic: 1.6, serene: 1.5, euphoric: 1.1 },
    energyRange: [0.32, 0.82],
    crop: { x: 0.48, y: 0.56, scale: 1.04 },
    curatorNote: "Coastal force without beach gloss; rock, salt, and air.",
  },
  {
    id: "tidal_mineral-aic-24645",
    bucket: "tidal_mineral",
    title: "Under the Wave off Kanagawa",
    artist: "Katsushika Hokusai",
    year: "1830/33",
    source: "aic",
    sourceId: "24645",
    sourceUrl: "https://www.artic.edu/artworks/24645",
    imagePath: "/artworks/tidal_mineral/aic-24645-great-wave-kanagawa.jpg",
    license: "CC0",
    tags: ["wave", "woodblock", "water", "printed_signal", "hypnotic", "surf rock", "breakbeat"],
    genreWeights: {
      "surf rock": 2.5,
      "drum and bass": 1.3,
      breakbeat: 1.2,
      "koto and shakuhachi": 1,
      "gamelan ensemble": 0.8,
    },
    moodWeights: { hypnotic: 2, euphoric: 1.3, mysterious: 1, serene: 0.8 },
    energyRange: [0.45, 0.9],
    crop: { x: 0.48, y: 0.52, scale: 1.05 },
    curatorNote: "A canonical print used for high-motion water and line energy.",
  },
  {
    id: "sublime_terrain-aic-146701",
    bucket: "sublime_terrain",
    title: "Mountain Brook",
    artist: "Albert Bierstadt",
    year: "1863",
    source: "aic",
    sourceId: "146701",
    sourceUrl: "https://www.artic.edu/artworks/146701",
    imagePath: "/artworks/sublime_terrain/aic-146701-mountain-brook.jpg",
    license: "CC0",
    tags: ["mountain", "forest", "sublime", "cinematic film score", "epic orchestral", "triumphant"],
    genreWeights: {
      "cinematic film score": 2.6,
      "epic orchestral": 2.8,
      "post-rock": 2.3,
      "psychedelic rock": 1.1,
    },
    moodWeights: { triumphant: 2.5, mysterious: 1.8, starlit: 1.4, brooding: 1.2 },
    energyRange: [0.45, 0.95],
    crop: { x: 0.5, y: 0.44, scale: 1.15 },
    curatorNote: "Sublime terrain for songs that need vertical scale and awe.",
  },
  {
    id: "nocturne_metro-aic-56905",
    bucket: "nocturne_metro",
    title: "Nocturne: Blue and Gold - Southampton Water",
    artist: "James McNeill Whistler",
    year: "1872",
    source: "aic",
    sourceId: "56905",
    sourceUrl: "https://www.artic.edu/artworks/56905",
    imagePath: "/artworks/nocturne_metro/aic-56905-nocturne-blue-and-gold.jpg",
    license: "CC0",
    tags: ["nocturne", "night", "water", "smoky", "trip hop", "deep house", "rain"],
    genreWeights: {
      "trip hop": 2.5,
      "deep house": 2.2,
      synthwave: 1.7,
      "city pop": 1.4,
      "UK garage": 1.3,
    },
    moodWeights: { smoky: 2.6, brooding: 2, melancholic: 1.8, starlit: 1.7 },
    energyRange: [0.35, 0.86],
    crop: { x: 0.5, y: 0.5, scale: 1.06 },
    curatorNote: "A wet, dim field for modern rain, night drives, and smoky beats.",
  },
  {
    id: "nocturne_metro-aic-20684",
    bucket: "nocturne_metro",
    title: "Paris Street; Rainy Day",
    artist: "Gustave Caillebotte",
    year: "1877",
    source: "aic",
    sourceId: "20684",
    sourceUrl: "https://www.artic.edu/artworks/20684",
    imagePath: "/artworks/nocturne_metro/aic-20684-paris-street-rainy-day.jpg",
    license: "CC0",
    tags: ["rain", "street", "urban", "city pop", "trip hop", "melancholic"],
    genreWeights: {
      "city pop": 2.1,
      "trip hop": 1.8,
      "deep house": 1.4,
      synthwave: 1.2,
      "UK garage": 1.2,
    },
    moodWeights: { melancholic: 2.1, smoky: 1.8, brooding: 1.4, starlit: 1 },
    energyRange: [0.32, 0.78],
    crop: { x: 0.56, y: 0.5, scale: 1.12 },
    curatorNote: "The explicit wet-city anchor; strong figures, so used with tighter crop.",
  },
  {
    id: "printed_signal-aic-33398",
    bucket: "printed_signal",
    title: "Iris, from Hokusai shashin gafu",
    artist: "Katsushika Hokusai",
    year: "c. 1814",
    source: "aic",
    sourceId: "33398",
    sourceUrl: "https://www.artic.edu/artworks/33398",
    imagePath: "/artworks/printed_signal/aic-33398-hokusai-iris.jpg",
    license: "CC0",
    tags: ["woodblock", "botanical", "archive", "line", "koto and shakuhachi", "minimal techno"],
    genreWeights: {
      "koto and shakuhachi": 2.6,
      "gamelan ensemble": 1.8,
      "guzheng meditation": 2.2,
      "baroque chamber strings": 1.5,
      "minimal techno": 1.4,
    },
    moodWeights: { mysterious: 2, hypnotic: 1.8, serene: 1.6, playful: 1 },
    energyRange: [0.2, 0.78],
    crop: { x: 0.5, y: 0.5, scale: 1.08 },
    curatorNote: "Printed line and botanical signal for sparse or ritual textures.",
  },
  {
    id: "printed_signal-met-37193",
    bucket: "printed_signal",
    title: "Seaside Village in Winter",
    artist: "Katsushika Hokusai",
    year: "1814",
    source: "met",
    sourceId: "37193",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/37193",
    imagePath: "/artworks/printed_signal/met-37193-hokusai-seaside-village-winter.jpg",
    license: "Public Domain",
    tags: ["woodblock", "winter", "mountains", "landscape", "mysterious", "serene"],
    genreWeights: {
      "koto and shakuhachi": 2.4,
      "guzheng meditation": 2,
      "gamelan ensemble": 1.8,
      "baroque chamber strings": 1.3,
    },
    moodWeights: { serene: 2, mysterious: 1.8, melancholic: 1.3, weightless: 1.2 },
    energyRange: [0.2, 0.72],
    crop: { x: 0.5, y: 0.48, scale: 1.06 },
    curatorNote: "A quiet winter print for line-based calm and distance.",
  },
  {
    id: "interior_reverie-aic-28560",
    bucket: "interior_reverie",
    title: "The Bedroom",
    artist: "Vincent van Gogh",
    year: "1889",
    source: "aic",
    sourceId: "28560",
    sourceUrl: "https://www.artic.edu/artworks/28560",
    imagePath: "/artworks/interior_reverie/aic-28560-van-gogh-the-bedroom.jpg",
    license: "CC0",
    tags: ["interior", "bedroom", "window", "cozy", "lo-fi hip hop", "music box lullaby"],
    genreWeights: {
      "lo-fi hip hop": 2.3,
      "music box lullaby": 2,
      "solo piano": 1.7,
      "neo-soul": 1.4,
      "dream pop instrumental": 1.3,
    },
    moodWeights: { cozy: 2.6, nostalgic: 2, bittersweet: 1.8, melancholic: 1.2 },
    energyRange: [0.2, 0.62],
    crop: { x: 0.52, y: 0.5, scale: 1.08 },
    curatorNote: "The private-room anchor for bedroom, lullaby, and lo-fi songs.",
  },
  {
    id: "stage_heat-aic-27992",
    bucket: "stage_heat",
    title: "A Sunday on La Grande Jatte - 1884",
    artist: "Georges Seurat",
    year: "1884-86",
    source: "aic",
    sourceId: "27992",
    sourceUrl: "https://www.artic.edu/artworks/27992",
    imagePath: "/artworks/stage_heat/aic-27992-sunday-la-grande-jatte.jpg",
    license: "CC0",
    tags: ["crowd", "leisure", "pointillism", "euphoric", "disco", "funk groove", "swing jazz"],
    genreWeights: {
      "funk groove": 2,
      disco: 2.2,
      "swing jazz": 1.8,
      "jazz fusion": 1.5,
      breakbeat: 1.1,
    },
    moodWeights: { euphoric: 2.2, playful: 2, triumphant: 1.2, glowing: 1.2 },
    energyRange: [0.5, 0.98],
    crop: { x: 0.52, y: 0.52, scale: 1.1 },
    curatorNote: "Public rhythm and heat, but still painterly rather than party stock.",
  },
  {
    id: "hypermodern_void-aic-65916",
    bucket: "hypermodern_void",
    title: "Movement",
    artist: "Marsden Hartley",
    year: "1913",
    source: "aic",
    sourceId: "65916",
    sourceUrl: "https://www.artic.edu/artworks/65916",
    imagePath: "/artworks/hypermodern_void/aic-65916-marsden-hartley-movement.jpg",
    license: "CC0",
    tags: ["modernism", "abstract", "geometric", "hypnotic", "minimal techno", "synthwave"],
    genreWeights: {
      synthwave: 2.2,
      "ambient electronic": 1.8,
      "minimal techno": 2.5,
      vaporwave: 1.8,
      chillwave: 1.3,
      "drum and bass": 1.2,
      breakbeat: 1.1,
    },
    moodWeights: { hypnotic: 2.5, weightless: 1.9, starlit: 1.7, mysterious: 1.5 },
    energyRange: [0.35, 0.95],
    crop: { x: 0.5, y: 0.5, scale: 1.05 },
    curatorNote: "Early abstraction as the first hypermodern anchor, before adding self-made voids.",
  },
] as const satisfies readonly ArtworkCatalogEntry[];
